# This is a basic workflow to help you get started with Actions

name: CI-testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'
        activate-environment: test-environment
        python-version: 3.6.10
        auto-activate-base: false
        auto-update-conda: true
        condarc-file: test/condarc.yml

    - name: Use Node JS 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Install JS dependencies
      run: |
        npm ci
        npm install bower
        ./node_modules/bower/bin/bower install

    - name: Install Narrative Application
      shell: bash -l {0}
      run: |
          bash ./scripts/install_narrative.sh
          grunt minify
          sed <src/config.json.templ >src/config.json "s/{{ .Env.CONFIG_ENV }}/dev/"
          sed -i 's/{{ if ne .Env.CONFIG_ENV "prod" }} true {{- else }} false {{- end }}/true/' src/config.json
          jupyter notebook --version

    - name: Run Narrative Test Suite
      shell: bash -l {0}
      env:
        KBASE_TEST_TOKEN: ${{ secrets.NARRATIVE_TEST_TOKEN }}
      run: make test

    - name: Send to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: |
          ./coverage.xml
          ./js-coverage/lcov/lcov.info
        fail_ci_if_error: true
